services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    restart: always

  workerservice:
    image: hudz3103/deliveryservice-image # Docker Hub image
    container_name: workerservice
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - backend
    restart: always
    volumes:
      - shippingdata:/app/data

  shipmentdelivery:
    image: jabir8210/shipping-serice-image1 # Docker Hub image
    container_name: shipmentdelivery
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - backend
    restart: always
    volumes:
      - shippingdata:/app/data

networks:
  backend:
    driver: bridge

volumes:
  shippingdata:
