services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    restart: always

  workerservice:
    image: hudz3103/deliveryservice-image1
    container_name: workerservice
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - backend
    restart: always
    volumes:
      - shippingdata:/app/data

  shipmentdelivery:
    image: hudz3103/shipping-service:latest
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - "5000"
    networks:
      - backend
    restart: always
    volumes:
      - shippingdata:/app/data

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./load-test-env/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - shipmentdelivery
    ports:
      - "4000:4000"
    networks:
      - backend
    restart: always

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - backend
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - backend
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  shippingdata:
  mongodata:
