services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    restart: always

  workerservice:
    image: hudz3103/deliveryservice-image1
    container_name: workerservice
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - backend
    restart: always
    volumes:
      - shippingdata:/app/data

  shipmentdelivery:
    image: jabir8210/shipping-serice-image1
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_URLS=http://+:5000
    expose:
      - "5000"
    networks:
      - backend
    restart: always
    volumes:
      - shippingdata:/app/data

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./load-test-env/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - shipmentdelivery
    ports:
      - "4000:4000"
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  shippingdata:
