name: Byg et Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker_image_pipeline:
    name: Build Docker image to Docker Hub
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    env:
      IMAGE_NAME: delivery-service

    steps:
      # 📦 Henter projektets kode
      - name: Checkout kode
        uses: actions/checkout@v4

      # 🏷️ Udtrækker versionen fra .csproj-filen
      - name: Extract version from .csproj
        id: extract_version
        run: |
          VERSION=$(grep '<InformationalVersion>' ServiceWorker.csproj | sed -E 's/.*<InformationalVersion>(.*)<\/InformationalVersion>.*/\1/')
          VERSION=${VERSION:-latest}
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 🔐 Logger ind på Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 🛠️ Bygger og pusher Docker image med version-tag
      - name: Build and push Docker image
        run: |
          VERSION=${{ steps.extract_version.outputs.version }}
          IMAGE=${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:$VERSION

          echo "Bygger Docker image: $IMAGE"
          docker build -f Dockerfile -t $IMAGE .
          docker push $IMAGE
